### ISSUE TITLE
Filter view with not enough samples

### ISSUE THREAD

**Issue by ahmetrifaioglu** [saezlab/MOFAcellulaR#2]
a filtering step before feature filtering to avoid errors if cell-types are not defined beforehand

**Comment by roramirezf** [comment]
I have added two new functions in the latest commit 52929f4 to deal with the filtering of complete views:

`filt_views_bysamples()` and `filt_views_bysamples()` that can be run after 'filt_gex_byexpr()' and 'filt_profiles()' respectively
