### ISSUE TITLE
Making the pseudobulk column name parametric 

### ISSUE THREAD

**Issue by ahmetrifaioglu** [saezlab/MOFAcellulaR#3]
MOFACell crashes when creating the cell-type list into a MOFA ready object (i.e. `MOFAcellulaR::pb_dat2MOFA`) if a different column name is used other than "donor_id" for pseudobulking

**Comment by roramirezf** [comment]
Added parameter in [3118854](https://github.com/saezlab/MOFAcellulaR/commit/3118854ef1dfe4d94134d649c9b7b618aa34af3c)
